INSERT INTO cliente (id, nome, email) VALUES (1, 'Victor', 'Lindo@email.com')
INSERT INTO cliente (id, nome, email) VALUES (2, 'Amaral', 'e@email.com')
INSERT INTO cliente (id, nome, email) VALUES (3, 'Freitas', 'obs@email.com')
INSERT INTO cliente (id, nome, email) VALUES (4, 'ok', 'belo@email.com')
INSERT INTO cliente (id, nome, email) VALUES (5, 'zero', 'nome@email.com')